\input{../header}

% \mode<beamer>{\usetheme{AnnArbor}}
\mode<beamer>{\usetheme{metropolis}}
\mode<beamer>{\metroset{block=fill}}
% \mode<beamer>{\usecolortheme{wolverine}}

\mode<beamer>{\setbeamertemplate{section in toc}[sections numbered]}
\mode<beamer>{\setbeamertemplate{subsection in toc}[subsections numbered indented]}

% \mode<beamer>{\usefonttheme{serif}}
\mode<beamer>{\setbeamertemplate{footline}}
\mode<beamer>{\setbeamertemplate{footline}[frame number]}
\mode<beamer>{\setbeamertemplate{frametitle continuation}[from second][\insertcontinuationcountroman]}
\mode<beamer>{\setbeamertemplate{navigation symbols}{}}

\mode<handout>{\pgfpagesuselayout{2 on 1}[letterpaper,border shrink=5mm]}

\newcommand\CHAPTER{3}
% \newcommand\answer[2]{\textcolor{blue}{#2}} % to show answers
% \newcommand\answer[2]{\textcolor{red}{#2}} % to show answers
 \newcommand\answer[2]{#1} % to show blank space

\title{\vspace{2mm} \link{https://jeswheel.github.io/5200_f26/}{Stat 5200: Analysis of Designed Experiments}}
\author{Jesse Wheeler}
\date{}

\setbeamertemplate{footline}[frame number]

<<setup,include=FALSE,cache=FALSE,purl=FALSE,child="../setup.Rnw">>=
@

\begin{document}

\maketitle

\mode<article>{\tableofcontents}

% \mode<presentation>{
%   \begin{frame}{Outline}
%     \tableofcontents
%   \end{frame}
% }

\section{Overview}

\begin{frame}[allowframebreaks]{Objectives and overview}
  \begin{itemize}
    \item This material is based Chapter~3 on the textbook ``A First Course in Design and Analysis of Experiments" \citep{oehlert2000}.
    \item Chapter outcomes include: 
    \begin{itemize}
      \item TODO
    \end{itemize}
  \end{itemize}
\end{frame}

\section{Completely Randomized Designs}

\begin{frame}[allowframebreaks]{Completely Randomized Design}
  \begin{itemize}
    \item Completely randomized design (CRD) is the simplest design for comparing treatments and is sometimes the preferred design. 
    \item \alert{Setup:}
    \begin{itemize}
      \item There are $g$ treatment groups.
      \item $N$ experimental units (EU)s available.
      \item You want sample sizes of $n_1, n_2, \ldots, n_g$, with $\sum_{i = 1}^g n_i = N$. 
    \end{itemize}
  
  \framebreak
  
    \item \alert{Idea}: All possible sub-group composition are equally as likely. 
  \end{itemize}
  
  \begin{block}{Performing a Completely Randomized Design}
    \begin{itemize}
      \item Randomly choose $n_1$ EU's for treatment $1$.
      \item Randomly choose $n_2$ EU's for treatment $2$.
      \item $\ldots$
      \item Randomly choose $n_{g-1}$ EU's for treatment $g-1$.
      \item The remaining $n_g$ EU's are assigned to treatment $g$.
    \end{itemize}
  \end{block}
  
  \begin{itemize}
    \item On a computer, this can be done by permuting $1, 2, \ldots, N$, and assigning the first $n_1$ numbers to treatment 1, the next $n_2$ to treatment 2, etc.
  \end{itemize}
  
\end{frame}

\begin{frame}[allowframebreaks]{Advantages and Disadvantages}
  \begin{itemize}
    \item Advantages
    \begin{itemize}
      \item Simple to do; all you need is one random permutation.
      \item Simple to explain and understand.
      \item Simple to analyze.
      \item No restrictions on the sample sizes (other designs may restrict $n_i$).
      \item Easy with missing values.
    \end{itemize}
    \item Disadvantages
    \begin{itemize}
      \item Not always possible or cost-effective.
      \item The accuracy of the experiment depends on variability among the EUs, not just the variability among treatment groups. Thus, it may require more EUs (\$\$\$\$).
    \end{itemize}
  \end{itemize}
\end{frame}

\begin{frame}[allowframebreaks]{Example: Acid Rain}
  \cite{wood74} studied the effect of acid rain on trees. 
  One experiment used 240 six-week-old yellow birch seedlings. These seedlings were divided into five groups of 48 \emph{at random}, and the seedlings within each group received an acid mist treatment 6 hours a week for 17 weeks.
  The five treatments differed by mist pH: 4.7, 4.0, 3.3, 3.0, and 2.3. Othwerwise, the seedlings were treated identically.
  After the 17 weeks, the seedlings were weighed, and total plant (dry) weight was taken as response.
  
  \textbf{Questions:}
  
  \begin{itemize}
    \item What type of design is this, and can you describe why?
    \item What are the EUs, and how many are there?
    \item What was the response?
  
  \framebreak
    \item What compromises may have been made in this case?
    
    \mode<article>{
      \begin{itemize}
        \item Damage may vary by pH level, plant developmental stage, plant species, etc., yet only pH level was directly addressed.
        \item The study wishes to study the impact of acid-rain, but the available treatment was a synthetic acid rain, which may have a slightly different impact.
        \item Total plant weight is an important response, but other responses measuring tree health may also be available.
      \end{itemize}
        }
        
        \mode<presentation>{\vspace{2cm}}
        
        Like many experiments, the researchers necessarily have to narrow down an enormous question to a workable experiment using artificial acid rain under controlled conditions.
        For any experiment, a considerable amount of non-statistical background work goes into the planning even the simplest experiment. 
  
  \end{itemize}
\end{frame}

\section{Models and Parameters}

\begin{frame}[allowframebreaks]{Introduction and definitions}
  \begin{itemize}
    \item All formal statistical analysis is based on probability models.
    \item \emph{EX:} The number of heads in ten tosses of a fair coin would be Binomial$(10, 0.5)$. Here, the model depends on 2 parameters: $N = 10$ the number of trials, $p = 0.5$ is the probability of heads.
    \item In an experiment, we may posit several different models for the data, all with \emph{unknown} parameters. 
    One of our objectives is often to describe which model is the best description of the data, and make \emph{inference} about parameters.
  \end{itemize}
  
  \begin{block}{Definition: Inference}
    Using data to learn properties of a probability distribution. In our case, using data to estimate parameters of a model.
  \end{block}
  
  \framebreak
  
  \begin{itemize}
    \item The models we will consider for experimental design will have two basic parts:
    \begin{itemize}
      \item A description of the expected value, or mean, of the data. Sometimes called ``model for the means".
      \item A description of how data vary around the treatment means. Sometimes called `model for the errors". 
    \end{itemize}
    \item For the errors, we will generally assume that they are independent for different data values, have mean zero, and all have a common variance $\sigma^2$.
    \item To perform formal tests and obtain confidence intervals, we will further assume a distribution of the errors.
    Generally, we assume that the errors follow a \alert{Gaussian} (Normal) distribution.
  \end{itemize}
  
  \framebreak

  \begin{itemize}
    \item For a CRD, we start with two basic models. 
    \item Recall: $g$ treatment groups, $N$ EUs.
  \end{itemize}
    
    \mode<presentation>{
      % \item Let $y_{ij}$ be the $j$th response, $i$th treatment group.
      \begin{enumerate}
        \item \alert{The Full Model} (separate group means)

      \framebreak

        \item \alert{The Reduced Model} (single mean model)

     \end{enumerate}

    \framebreak
    }
    
    \mode<article>{
      Let $y_{ij}$ be:
      \begin{itemize}
        \item The $j$th response,
        \item In the $i$th treatment group.
      \end{itemize}
      Thus, $i$ runs between 1 and $g$, and $j$ runs between $1$ and $n_i$, in treatment group $i$.
      There are many possible models for the mean-treatment effect that we could consider.
      We will focus on two basic ones:
      \begin{enumerate}
        \item We assume that each treatment has its own mean response $\mu_i$, and that the errors are normally distributed.
        These assumptions give rise to the \emph{model for the data}:
      $$
      y_{ij} \sim N\big(\mu_i, \sigma^2\big).
      $$
      We can alternatively write this same model as:
      $$
      y_{ij} = \mu_i + \epsilon_{ij},
      $$
      where $\epsilon_{ij} \sim N(0, \sigma^2)$ are the independent, normally  distributed errors with mean zero and variance $\sigma^2$.
      \begin{itemize}
        \item This is a model with separate group means, which we will sometimes call the \alert{full model}.
      \end{itemize}
      \item The next basic model for the means is the \alert{single mean model}, also called the \alert{reduced} model.
      This model assumes all treatments have the same mean, $\mu$.
      Combined with the error structure, the single mean model implies that the data are independent and normally distributed with mean $\mu$ and constant variance $\sigma^2$:
      $$
      y_{ij} \sim N(\mu, \sigma^2).
      $$
      Again, we may alternatively write this model as:
      $$
      y_{ij} = \mu + \epsilon_{ij}, \quad \epsilon_{ij} \sim N(0, \sigma^2).
      $$
      \begin{itemize}
        \item Note that this single mean model is a special case (or restriction) of the group means model: all of the $\mu_i$s equal eachother.
        \item \alert{Model comparison is easiest when one of the models is a restricted or reduced form of the other!}
      \end{itemize}
      \end{enumerate}
    }
    
\end{frame}

\begin{frame}[allowframebreaks]{Defining overall mean}

  \begin{itemize}
  
  \item It's sometimes useful to express the group means $\mu_i$ as:
        $$
        \mu_i = \mu^* + \alpha_i.
        $$
        In this case, we call $\mu^*$ the \emph{overall mean}, and the $\alpha_i$'s are the $i$th \emph{treatment effects}.
        
  \mode<presentation>{\item This introduces an extra parameter (g+1 total), which we need to address. Generally, we do this by defining $\mu^*$ and require that $\alpha_i = \mu_i - \mu^*$.}
        
        \mode<article>{
        The restricted model in this case implies $\alpha_i = 0$ for all $i \in 1:g$.
        
        Note that if there are $g$ $\alpha_i$'s, and one overall mean $\mu^*$, this means there are $g+1$ parameters.
        This is problematic because they are not uniquely determined.
        We will avoid this issue by imposing an additional mathematical structure on the set of $g$ group means.
        Specifically, we either define $\mu^*$ and require that $\alpha_i = \mu_i - \mu^*$, or we define $\alpha_i$ and then set $\mu^* = \mu_i - \alpha_i$.
        These are really just two-sides of the same coin, and mathematically give us the same information.
        However, some software will do one or the other, and you should think carefully about what's happening.
        Ultimately it doesn't matter as long as we can identify which choice is in use at any given time.
        That is, as long as we can determine the treatment means, the differences of treatment means, and compare the models, it doesn't matter.
        }
        
        \framebreak
        
        \item One classic choice is to define $\mu^*$ as the mean of the treatment means:
        
        \framebreak
        \mode<article>{
        $$
        \mu^* = \sum_{i = 1}^g \mu_i / g,
        $$
        which, defining $\alpha_i = \mu_i - \mu^*$, implies
        $$
        \sum_{i = 1}^g \alpha_i = 0.
        $$
        }
        
        \item An alternative choice (that can sometimes make hand-work simpler) instead describes $\mu^*$ as the weighted average:
        
        \mode<article>{
        $$
        \mu^* = \sum_{i = 1}^g n_i \mu_i / N,
        $$
        in which case the weighted sum of the treatment effects will be zero:
        $$
        \sum_{i = 1}^g n_i \alpha_i =  0.
        $$
        In our current model, defining $\alpha_i$ is a bit of an over-complication, but it will be useful later.
        }
        
        \framebreak
        
        \item Another common choice in software is to set $\mu^* = \mu_j$, for some $j \in 1:g$. Many software just use the last mean: $\mu^* = \mu_g$.
        
        \mode<article>{
        With this choice, we still have our standard restriction:
        $$
        \alpha_i = \mu_i - \mu^*, \quad \text{for all } i \in 1:g.
        $$
        Thus, we have:
        $$
        \alpha_i = \begin{cases}
          \mu_j - \mu_j = 0 & \text{if } i = j \\
          \mu_i - \mu_j & \text{otherwise}
        \end{cases}
        $$
        
        Importantly, it doesn't really matter which is used as long as you know the version being used. You can always re-frame / recover the other form if you prefer it.
        For instance, the last option is particularly useful if treatment $j$ is some form of control; this way, the treatment effect is always compared to the control.
        
        Notably, the added constraints on $\alpha_i$s imply that not all are free to vary.
        With $\mu^*$ being fixed (or pre-selected), only $g-1$ of them are free to vary, the last treatment effect is then determined by whatever is needed to satisfy the constraint.
        We express this by saying that the treatment effects have $g-1$ \alert{degrees of freedom}.
        }
        
      \end{itemize}

    
\end{frame}

\begin{frame}{Model Recap}
  However you choose to define $\mu^*$ and $\alpha_i'$s, we end up with the following models for the data:
  
  \begin{itemize}
    \item \emph{The full model}:
    $$
    y_{ij} = \mu^* + \alpha_i + \epsilon_{ij}
    $$
    \item \emph{The reduced model}:
    $$
    y_{ij} = \mu + \epsilon_{ij}
    $$
  \end{itemize}
\end{frame}

\section{Parameter Estimation}

\begin{frame}[allowframebreaks]{Estimating parameters}
  \begin{itemize}
    \mode<article>{\item We now want to consider how to compare these two models using data. The classic tool that we will be using is called ANalysis Of VAriance (ANOVA). In practice, we will just be using some form of statistical software (in this class, it will be R). Part of the output of ANOVA will be parameter estimates and other important statistics, so we will first describe what these estimates are and how we express them mathematically.}
    \item We want to use data to estimate $\mu_i$'s and the variance $\sigma^2$. From these, we'll compute $\mu^*$ and $\alpha_i$'s.
    \item We will focus on computing \alert{unbiased} estimates of these parameters. \mode<article>{Though there is a technical definition of \emph{unbiased estimators}, we will simply use this to mean that if we were to average the values of the estimates across all \emph{potential} random errors, we would get the true parameter values.}
    \mode<article>{We will use the ``hat" notation ($\hat{\bullet}$) throughout the class, to distinguish a true parameter value from it's estimate. For instance, $\hat{\mu}$ is an estimator of $\mu$.}
    \item Estimate for $\mu_i$:
    \mode<article>{
      $$\hat{\mu}_i = \bar{y}_{i \bullet} = \frac{1}{n_i}\sum_{j = 1}^{n_i} y_{ij}$$
    }\mode<presentation>{\vspace{2cm}}
    \item The estimate for $\mu^*$ is fixed, so it depends on how we defined it.
    
    \framebreak
    
    \mode<article>{
      \begin{itemize}
        \item Unweighted average.
        $$
        \hat{\mu}^* = \frac{1}{g}\sum_{i = 1}^{n_i} \hat{\mu}_i = \frac{1}{g}\sum_{i = 1}^{n_i}\bar{y}_{i\bullet},
        $$
        $$
        \hat{\alpha}_j = \hat{\mu}_j - \hat{\mu}^* = \bar{y}_{j\bullet} - \frac{1}{g}\sum_{i = 1}^{n_i} \bar{y}_{i\bullet}
        $$
        \item Weighted average.
          $$\hat{\mu}^* = \frac{1}{N} \sum_{i = 1}^g n_i \hat{\mu}_i \\
                      = \frac{1}{N} \sum_{i = 1}^g n_i \bar{y}_{i\bullet} \\
                      = \frac{1}{N} \sum_{i = 1}^g \sum_{j = 1}^{n_i} y_{ij} \\
                      = \bar{y}_{\bullet \bullet}$$
        $$
        \hat{\alpha}_j = \hat{\mu}_j - \hat{\mu}^* = \bar{y}_{j\bullet} - \bar{y}_{\bullet \bullet}
        $$
        \item Reference Group.
        $$
        \hat{\mu}^* = \hat{\mu}_j = \bar{y}_{j\bullet}
        $$
        $$
        \hat{\alpha}_j = \hat{\mu}_j - \hat{\mu}^* = 0
        $$
        $$
        \hat{\alpha}_i = \hat{\mu}_i - \hat{\mu}^* = \bar{y}_{i\bullet} - \bar{y}_{j \bullet}
        $$
      \end{itemize}
    }
    
    \mode<presentation>{
    \item Unweighted average
    
    \vfill
    
    \item Weighted average
    
    \vfill
    
    \item Reference Group
    
    \vfill
    }
    
  \framebreak
  
  \item The only parameter left to estimate is $\sigma^2$:
  \mode<article>{
  $$
  \hat{\sigma}^2 = \text{MS}_\text{E} = \frac{\text{SS}_\text{E}}{N - g} = \frac{\sum_{i = 1}^g \sum_{j = 1}^{n_i}(y_{ij} - \bar{y}_{i\bullet})^2}{N-g}
  $$
  We use the notation $\text{SS}_\text{E}$ to denote the ``Sum of Squares for Error", and $\text{MS}_{\text{E}}$ to mean the ``Mean Square for Error".
  The denominator includes $N-g$ as the number of \alert{degrees of freedom}.
  Consider the summand: $(y_{ij} - \bar{y}_{i\bullet})^2$. This is the deviations from the group mean, and they must add to zero in any group. 
  Thus, any $n_i - 1$ of them determine the remaining value, so that in each group, there are only $n_i - 1$ degrees of freedom, or that there are $N - g$ degrees of freedom for error for the experiment.
  }
  
  \framebreak
  
  \item Above, we have described \alert{point estimates}. In some sense, these are our ``best guess" as to the value of a particular parameter.
  \item We also want some measure of uncertainty of this estimate. The standard frequentist way of doing this is a \alert{confidence interval}.
  
  
  \end{itemize}
  
\end{frame}

\newcommand\acknowledgments{
\begin{itemize}
\item   Compiled on {\today} using \Rlanguage version \Sexpr{getRversion()}.
\item   \parbox[t]{0.75\textwidth}{Licensed under the \link{http://creativecommons.org/licenses/by-nc/4.0/}{Creative Commons Attribution-NonCommercial license}.
    Please share and remix non-commercially, mentioning its origin.}
    \parbox[c]{1.5cm}{\includegraphics[height=12pt]{../cc-by-nc}}
\item We acknowledge \link{https://jeswheel.github.io/5200_f26/acknowledge.html}{students and instructors for previous versions of this course / slides}.
\end{itemize}
}

\mode<presentation>{
\begin{frame}[allowframebreaks=0.8]{References and Acknowledgements}
  
\bibliography{../bib5200}

\vspace{3mm}

\acknowledgments

\end{frame}
}

\mode<article>{

\newpage

{\bf \Large \noindent Acknowledgments}

\acknowledgments

\newpage

\bibliography{../bib5200}

}



\end{document}







