\documentclass[10pt,twoside]{article}
\usepackage[marginparsep=1em]{geometry}
\geometry{lmargin=1.0in,rmargin=1.0in, bmargin=1.2in,  tmargin=1.2in}
\usepackage[dvipsnames,svgnames,table]{xcolor}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{epstopdf}
\usepackage{verbatim}
\usepackage{enumerate}
\usepackage{bm}
\usepackage{amsthm}
\usepackage{float}
\usepackage{amsmath}
\usepackage{fancyhdr}
\usepackage{hyperref}
\usepackage{mathtools}
            
%%%%  SHORTCUT COMMANDS  %%%%
\newcommand{\ds}{\displaystyle}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\T}{\mathcal{T}}
\newcommand{\arc}{\rightarrow}
\newcommand{\R}{\mathbb{R}}
\newcommand{\RP}{\mathbb{R}(+)}
\newcommand{\Rs}{\mathbb{R}^{**}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\B}{\mathcal{B}}
\newcommand{\PX}{\mathcal{P}(X)}
\newcommand*\rot{\rotatebox{90}}
\newcommand*\OK{\ding{51}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\Answer}{\vspace{2mm}\textbf{\underline{Answer}}\\}
\newcolumntype{L}{>{$}l<{$}}
\newcolumntype{C}{>{$}c<{$}}
\newcommand{\GL}{\text{GL}}
\newcommand{\SL}{\text{SL}}

\newcommand{\stirling}[2]{\genfrac{\{}{\}}{0pt}{}{#1}{#2}}

\pagestyle{fancy}
\fancyhf{}
\renewcommand{\sectionmark}[1]{\markright{\thesection.\ #1}}
\lhead{\fancyplain{}{}} 
\fancyhead[RE,RO]{Stat 5200/6200, Fall 2026}
\fancyfoot[RE,RO]{\thepage}


\begin{document}
\begin{flushright}
\begin{minipage}{.33\textwidth}
\rightline{YOUR NAME}
\rightline{\href{mailto:YOUR EMAIL}{YOUR EMAIL}}
\rightline{\today}
\end{minipage}
\end{flushright}

\begin{center}
{\large{\textbf{Homework 1}}}
\end{center}

\begin{enumerate}
    \item If a researcher is conducting a paired experiment with exactly 12 participants, how many possible assignment combination must be evaluated to compute the exact randomization test?
    \item Using your own words, explain the primary advantages and disadvantages of a randomization test for performing inference compared to a standard parametric $t$-test.
    \item (Textbook, first edition) \textbf{Exercise 2.3}
    \item (Textbook, first edition) \textbf{Exercise 2.1}
    \begin{itemize}
      \item \textbf{[5200]} Instead of a randomization test, perform a two-sample $t$ test.
      \item \textbf{[6200]} Perform both a randomization test and a two-sample $t$ test.
    \end{itemize}
    
\end{enumerate}


\end{document}